### PR TITLE
perf(RHIF-171): Get rid of activeApps in redux

### PR DESCRIPTION
**Pull request by mkholjuraev**
# Description

Associated Jira ticket: # [RHIF-171](https://issues.redhat.com/browse/RHIF-171)

This PR removes AppInfo federated module usage together with rendering the SystemDetail component using activeApps in redux. Thus, making the application's complexity and performance.

NEEDS TO BE MERGED AFTER: https://github.com/RedHatInsights/insights-inventory-frontend/pull/1766

# How to test the PR

Run both PRs together and make sure no app breaks. Basic functionality should not change. Observe that the system details page works as expected.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [x] The commit message has the Jira ticket linked
- [x] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Review by gkarat — CHANGES_REQUESTED** [review]
Hey @mkholjuraev, I took a look and run the PR together with Inventory locally. I am afraid that the inventory details page doesn't load the Patch tab properly and throws errors (see the screenshot). I compared stage-stable (stage.foo.redhat.com:1337/insights/inventory vs console.stage.redhat.com/insights/inventory).

a message from the error that most probably caused the crash:
```
Uncaught (in promise) 
Object { title: "There was an error getting data", detail: "incorrect inventory_id format", status: 400 }
vendors-node_modules_redux-promise-middleware_dist_es_index_js.32f0fccd2880bfa38c39.js:173:11
```
image

**Comment by mkholjuraev** [comment]
oh, there is the inventory app that has an inventory id different in useParams. Will do something about it.

**Review by adonispuente — APPROVED** [review]
PR works as intended, LGTM!

**Review by gkarat — APPROVED** [review]
LGTM! works fine locally with inventory deployed together. nothing to call out from the code TBH.

**Pull request merged**
