### PR TITLE
feat(SPM-624): open packages tab directly from systes page.

### PR DESCRIPTION
**Pull request by mkholjuraev**
This enables to open the Packages tab directly by clicking the package number on the Systems page.

To test:
1. Visit the Systems page,
2. click on a package number in the table
3. Observe that the packages tab is opened by default.
4. In any other case, the advisor tab is active by default.
5. When systems detail page is opened using URL, advisor tab should be active, page should not break.

### CODE REVIEW

**Review by leSamo — CHANGES_REQUESTED** [review]
Hmmm point of this PR works well, but it looks like Advisories table has a regression:
1. Go to System detail page, Advisories tab
2. Navigate to the next page in table
3. Notice the current page did not get changed and `page=1&page_size=20` parameters in the URL are being replicated.

**Comment by mkholjuraev** [comment]
@leSamo thank you for the review. I have fixed the regression hopefully.

**Comment by mkholjuraev** [comment]
@leSamo another review, please?

**Comment by mkholjuraev** [comment]
@RedHatInsights/team-interact it would be great if this gets an attention

**Comment by mkholjuraev** [comment]
I have reviewed the PR, looks like there are no regressions. Merging, ask the QA to verify in the associated ticket.

**Pull request merged**
