### PR TITLE
chore: Update npm run start scripts and documentation

### PR DESCRIPTION
**Pull request by gkarat**
no jira.

This is a quick PR that aims to make npm run start* scripts consistent across Insights frontend applications.

### CODE REVIEW

**Comment by gkarat** [comment]
Relates to https://github.com/RedHatInsights/vulnerability-ui/pull/2013

**Comment by gkarat** [comment]
@mkholjuraev, could you please help me checking if dev.webpack.config.js contains all the necessary parameters? For now, I put only those that are common across all apps. I am not sure about some extra ones that Patch added like useCloud or useFileHash. Since you are more experienced with Patch, you might have more insights if these parameters are used at all and if we need to keep them further

**Review by mkholjuraev — COMMENTED** [review]
The app runs pretty well. According to team's decision, we can keep or remove following params:

1. useFileHash: this is needed to turn on caching in dev env and platform advices to do so. Ref: [consuming-module](http://front-end-docs-insights.apps.ocp4.prod.psi.redhat.com/fed/consuming-module) 
2. debug: as this is dev env, do we want to have debug mode enabled?
3. proxyVerbose: this is intended for the output of what the proxy is doing when we run the app. I am not sure if we need it (Attached image)

**Pull request merged**
