### PR TITLE
fix: remaining insights.chrome references

### PR DESCRIPTION
**Pull request by johnsonm325**
# Description

Associated Jira ticket: # (issue)

Please include a summary of the change, what this fixes/creates/improves.

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Review by gkarat — COMMENTED** [review]
there is one place where we still keep insights.chrome call: https://github.com/johnsonm325/patchman-ui/blob/fix-rest-insights-dot-chrome/src/Utilities/constants.js#L35 (gonna fix it and commit to this PR)

**Comment by mkholjuraev** [comment]
One more commit is coming...

**Review by mkholjuraev — APPROVED** [review]
LGTM! tested locally

**Comment by Fewwy** [comment]
LGTM, tried it locally and haven't found any insights.chrome warnings.

**Review by Fewwy — APPROVED** [review]

**Pull request merged**
