### PR TITLE
fix(SPM-1358): Fixed responsiveness issues on dashbars

### PR DESCRIPTION
**Pull request by AsToNlele**
Advisories:
- Before
1-before

- After
1-after

Systems:
- Before
2-before
- After
2-after

### CODE REVIEW

**Review by bastilian — APPROVED** [review]
Nicely done! Thank you @AsToNlele!

**Comment by mkholjuraev** [comment]
@AsToNlele Can you please modify commit names so that they follow semantic release conventions. You can have a look at previos commit names. We use something like:
1. 'feat(AFFECTED_COMPONENT_NAME): your commit message' for new features,
2. 'fix(AFFECTED_COMPONENT_NAME): your commit message' for a bug fix.
3. 'chore(AFFECTED_COMPONENT_NAME): your commit message' for commits not intended to trigger semantic release build. For example a minor changes, cleanups...

**Comment by AsToNlele** [comment]
@mkholjuraev Sorry about that! Are the commit names correct now?

**Comment by mkholjuraev** [comment]
@AsToNlele the names look good. please merge the PR it looks good to go.

**Pull request merged**
