### PR TITLE
feat(RHIF-83: introduce loading icon on remediation button in Advisor…

### PR DESCRIPTION
**Pull request by mkholjuraev**
Partly resloves: https://issues.redhat.com/browse/RHIF-51.

It just introduces a loading icon while the remediation issues map is being built. There is a new ticket in the advisor to optimize the API requests to fetch the issues map.

### CODE REVIEW

**Review by adonispuente — APPROVED** [review]
Thank you, PR works as intended, nice organization. LGTM!

Just a side note, has it been considered to disable the remediate button if the selected items are remediable automatically by ansible? I know theres a popup that displays afterwards if all remediations are manual, but it takes a bit to get feedback from it. There could be a reason we dont do this, but I just wanted to through it out there and hear your thoughts!

**Comment by mkholjuraev** [comment]
@adonispuente thank you for the review! YOU are awesome!

**Comment by mkholjuraev** [comment]
@adonispuente in a good world we should not see that modal at all on Advisories page. That modal is poping up because of API request failure. I have asked the backend to fix that endpoint.

**Pull request merged**
