### PR TITLE
fix(Remediating): SPM-2000 - Selecting all systems selected filtered …

### PR DESCRIPTION
**Pull request by AsToNlele**
# Description

Associated Jira ticket: [SPM-2000](https://issues.redhat.com/browse/SPM-2000)

Selecting all systems while having filters remediates now correct amount of systems

# How to test the PR

1. Go to Patch Systems
2. Apply some filters
3. Select all
4. You can remediate only systems that have installable advisories, so ideally count how many systems have Installable advisories 
5. Remediate
6. Make sure the number of systems matches

# Before the change

When selecting all systems while having filters, wrong system count is remediated

# After the change

Correct amount is remediated

# Dependent work link

# Checklist:

- [x] The commit message has the Jira ticket linked
- [x] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Comment by leSamo** [comment]
For some reason every time I try to open Status filter and click on a checkbox the whole page freezes and the tab crashes later, and I quite can't put my finger on why it happens, can you add and remove Status filter without page hanging?

**Comment by leSamo** [comment]
@AsToNlele were you able to reproduce/fix the issue I mentioned in my previous comment? I believe the last force push was just a rebase, or did it include any changes?

**Comment by AsToNlele** [comment]
I wasn't able to reproduce, yeah I just rebased :smile:

**Comment by mkholjuraev** [comment]
@AsToNlele seems the issue has been resolved.

**Comment by mkholjuraev** [comment]
Probably we can close this :)

**Pull request closed without merging**
