### PR TITLE
Use rollup for lib build

### PR DESCRIPTION
**Pull request by karelhala**
This will improve libraru build to include multiple environments and allow easier treeshaking, once this library is used somewhere it will produce much smaller app bundle.

* [x] merge after #149

### CODE REVIEW

**Comment by karelhala** [comment]
ping @jiridostal

**Comment by jiridostal** [comment]
Could you please resolve the conflicts?

**Comment by karelhala** [comment]
@jiridostal done. I've released beta version of this package, to test it in inventory and it went splendidly! With this change and vuln change as well, the inventory UI dropped from 10MB to 3MB. (compressed from 2MB to 700KB).

**Comment by jiridostal** [comment]
Heh, that sounds really cool. Thank you for that!

**Pull request merged**
