### PR TITLE
Update banner text shown on System detail of Satellite managed system

### PR DESCRIPTION
**Pull request by leSamo**
Jira ticket: https://issues.redhat.com/browse/RHINENG-2487
Mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/vRxbVR3

### Before:
Screenshot from 2023-10-10 19-27-42

### After:
Screenshot from 2023-10-10 19-27-19

### CODE REVIEW

**Review by bastilian — APPROVED** [review]
LGTM! Thank you @leSamo!

**Comment by niyazRedhat** [comment]
@leSamo i am looking and trying to fix PR check failures

**Pull request merged**
