### PR TITLE
fix(BulkSelect): enable loading state when all entities selected

### PR DESCRIPTION
**Pull request by mkholjuraev**
This introduces a loading icon when all entities are selected using the bulk selector.

### CODE REVIEW

**Comment by AsToNlele** [comment]
Thank you for your PR!
I've found in some really rare occasions there are two labels visible, but it would show up randomly and very few times
image
Looks great otherwise!

**Comment by mkholjuraev** [comment]
@AsToNlele great catch! Can you tell in what cases, does this occur?

**Comment by AsToNlele** [comment]
I'm afraid its completely random, It happened to me on the first try and then after like 10 tries.

**Comment by mkholjuraev** [comment]
@AsToNlele the issue is fixed

**Comment by adonispuente** [comment]
The ' Select All’ option seems to be working perfectly fine, but the loading icon doesnt pop up when just clicking the empty square, even though clicking the empty square does the same action. I believe we should add this icon when clicking this button

**Comment by mkholjuraev** [comment]
@adonispuente thanks for the suggestion. I have enabled the loader for that action as well. Please have a look.

**Review by adonispuente — APPROVED** [review]
great PR, LGTM!

**Pull request merged**
