### PR TITLE
chore: refactor advisory systems table

### PR DESCRIPTION
**Pull request by mkholjuraev**
# Description

Associated Jira ticket: # (issue)

This PR is intended to refactor the advisory systems table to make the code cleaner. The refactor only divides existing code to 2 components AdvisorySystems and AdvisorySystemsTable. AdvisorySystems is a wrapper around the table and the remediation wizard. AdvisorySystemsTable is solely for the table functionality.

It also has the tests rewritten

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Comment by Fewwy** [comment]
It looks good, I ran the tests and they are passing. Do we need to update something in them?

**Comment by mkholjuraev** [comment]
Nope, the PR is ready to be reviewed and merged if everything is fine

**Comment by mkholjuraev** [comment]
You were right, somehow I did not push the commit for tests rewrite

**Pull request merged**
