### PR TITLE
fix(store): remove getState from reducer

### PR DESCRIPTION
**Pull request by jiridostal**

### CODE REVIEW

**Comment by jiridostal** [comment]
@mkholjuraev Tests are failing and I have no idea why, would you mind having a look?

**Comment by mkholjuraev** [comment]
Definitely! ci again not working and I am not able to make it run. I will have a look when I can fix it

**Comment by mkholjuraev** [comment]
I could not push my commit for the tests. I am mering and will create separate PR

**Review by mkholjuraev — APPROVED** [review]

**Pull request merged**
