### PR TITLE
fix(InventoryTable): RHINENG-2912 - Remove custom OS filter handling

### PR DESCRIPTION
**Pull request by bastilian**
# Description

Associated Jira ticket: #RHINENG-2912

Removes the custom handling for the OS filter for InventoryTables

# Before the change

https://github.com/RedHatInsights/patchman-ui/assets/7757/2c301da9-6150-41df-8690-42022b7de260

# After the change

https://github.com/RedHatInsights/patchman-ui/assets/7757/1a348481-62b6-4c56-8d4e-15933b5590b8

### CODE REVIEW

**Review by mkholjuraev — CHANGES_REQUESTED** [review]
Codewise looks clean. While testing, I found out that appliying rhel 8.8 does not filter the table correctly. I see that there are rhel 8.8 systems, but applying the filter results in an empty result.  It seems filtering syntax got affected, it has incorrect value : **in:in:RHEL 8.8**

**Comment by bastilian** [comment]
@mkholjuraev Thank you for reviewing and testing it! The filtering should now work as expected again.

**Review by mkholjuraev — APPROVED** [review]
LGTM! I see that the new function is covered with tests. We can enhance it more by writing tests that ensure that actvie OS filter indeed goes to the API request as expected.

**Pull request merged**
