### PR TITLE
feat(Tags): SPM-1178 add tags column, tag filter

### PR DESCRIPTION
**Pull request by mkholjuraev**

### CODE REVIEW

**Comment by mkholjuraev** [comment]
The global tag filter and local tag filter in the inventory table are unified, giving the privilege to the local tag.

**Comment by jiridostal** [comment]
obrazek

I see the Tags column is a bit misaligned. Btw is change of the order of columns intended?

**Comment by jiridostal** [comment]
obrazek

Here I see there is only one Tag available per row, but when I click it I see 6 tags

**Pull request merged**
