### PR TITLE
bug(StatusFilter): clear filters on unmount, solve 2x upgradable label

### PR DESCRIPTION
**Pull request by mkholjuraev**
Resolves: https://issues.redhat.com/browse/SPM-651 and https://issues.redhat.com/browse/SPM-697

### CODE REVIEW

**Comment by mkholjuraev** [comment]
Better to merge after https://issues.redhat.com/browse/SPM-703 is resolved.

**Comment by mkholjuraev** [comment]
The final solution is kind of hackish. SystemPackages and packages pages need to send their own filter object name and types.
I think it would be better if we have a short discussion about it later. 

In this commit, I removed clearing PackagesListStore as we have discussed.

**Comment by jiridostal** [comment]
Package detail page does not load with an error:
image

Also, isn't it nicer to have two separate filters than merging these two cases into one?

**Pull request merged**
