### PR TITLE
Enzyme tests refactored separated by commits

### PR DESCRIPTION
**Pull request by Fewwy**
This is the same as https://github.com/RedHatInsights/patchman-ui/pull/1123 PR but separated by commits/file changed

### CODE REVIEW

**Review by johnsonm325 — APPROVED** [review]
Approved. But I do have one question. It looks like the snapshots now remove the names of the child components and replaces them with pure html like `<h5>` and `<div>` rather than `<Breadcrumb>` and the like. Is this the kind of output we expect to see from RTL?

**Comment by Fewwy** [comment]
@johnsonm325 As far as I understand - yes

**Pull request merged**
